### ISSUE TITLE
localhost:8080 Says Loading and hangs up

### ISSUE THREAD

**Issue by srivatsan92** [Mawalu/whatsapp-phishing#1]
I installed all dependencies and pre requisite. Finally when I goto http://localhost:8080 , it says 'Loading' and never loads the page...

**Comment by aashraybhandar1** [comment]
Same here

**Comment by Mawalu** [comment]
Works for me. Maybe update selenium.

**Comment by petsod** [comment]
I also have the same problem, even after that i updated to a newer selenium
