### ISSUE TITLE
Page still shows only loading

### ISSUE THREAD

**Issue by aashraybhandar1** [Mawalu/whatsapp-phishing#2]
using selenium-server-standalone-2.53.1 the page stills shows just loading written on it

**Comment by noob2020** [comment]
selenium 2.53.1 need firefox 46

**Comment by duard** [comment]
I'm using Firefox 45

![selection_001](https://cloud.githubusercontent.com/assets/36894/18808988/56dd8dfa-8247-11e6-8b15-b6740dbed3a5.png)

**Comment by niklasbuschmann** [comment]
I'm genuinely and truly sorry, but this project is no longer actively maintained.

The "page still loading" bug seems to be very, very common, especially among users without much experience, but unfortunately it won't get fixed.

However you can feel free to create a pull request and we will gladly merge it.
