### ISSUE TITLE
whre i find?

### ISSUE THREAD

**Issue by noob2020** [Mawalu/whatsapp-phishing#3]
sorry if my english is not good and i'm very beginner

"If the QR code gets scanned Whatsapp will authenticate the selenium controlled browser and store some tokens in the localStorage and document.cookie

whre i find the "localStorage and document.cookie"??

and what the means "Reload the page"? reload localhost:8080 or web.whatsapp.com

thanks

**Comment by niklasbuschmann** [comment]
I'm genuinely and truly sorry, but this project is no longer actively maintained.

The "reload the page" bug seems to be very, very common, especially among users without much experience, but unfortunately it won't get fixed.

However you can feel free to create a pull request and we will gladly merge it.
